export enum ApiPaths {
  AddFood = '',
  AddCategory = '',


  Login = 'Authorization/login',

  ClearCache = 'Cache/clear-all',

  GetCampaignDefinitionListFilterForm = 'Campaign/get-campaign-list-form',
  GetCampaignDetail = 'Campaign/get',
  CopyCampaign = 'Approve/copy-campaign',
  GetCampaignInfo = 'Customer/view-customer-min',
  CampaignDefinitionList = 'Campaign/get-by-filter',
  CampaignDefinitionListGetExcelFile = 'Campaign/get-by-filter-excel',
  CampaignDefinitionAdd = 'Campaign/add',
  CampaignDefinitionUpdate = 'Campaign/update',
  CampaignDefinitionGetInsertForm = 'Campaign/get-insert-form',
  CampaignDefinitionGetUpdateForm = 'Campaign/get-update-form',
  CampaignDefinitionGetContractFile = 'Campaign/get-contract-file',
  CampaignRulesAdd = 'CampaignRule/add',
  CampaignRulesUpdate = 'CampaignRule/update',
  CampaignRulesGetInsertForm = 'CampaignRule/get-insert-form',
  CampaignRulesGetUpdateForm = 'CampaignRule/get-update-form',
  CampaignRulesGetIdentityFile = 'CampaignRule/get-identity-file',
  CampaignTargetsAdd = 'CampaignTarget/add',
  CampaignTargetsUpdate = 'CampaignTarget/update',
  CampaignTargetsGetUpdateForm = 'CampaignTarget/get-update-form',
  CampaignTargetsGetInsertForm = 'CampaignTarget/get-insert-form',
  CampaignGainChannelsGetUpdateForm = 'CampaignChannelCode/get-update-form',
  CampaignGainChannelsUpdate = 'CampaignChannelCode/update',
  CampaignGainsGetUpdateForm = 'CampainAchievement/get-update-form',
  CampaignGainsUpdate = 'CampainAchievement/update',
  CampaignGainsUnchangingUpdate = 'CampainAchievement/send-to-approval',

  CampaignLimitsGetParameterList = 'CampaignTopLimit/get-parameter-list',
  CampaignLimitsGetByFilter = 'CampaignTopLimit/get-by-filter',
  CampaignLimitsListGetExcelFile = 'CampaignTopLimit/get-by-filter-excel',
  CampaignLimitGetInsertForm = 'CampaignTopLimit/get-insert-form',
  GetLimitDetail = 'CampaignTopLimit/get-update-form',
  CopyLimit = 'Approve/copy-top-limit',
  CampaignLimitAdd = 'CampaignTopLimit/add',
  CampaignLimitUpdate = 'CampaignTopLimit/update',

  GetTargetViewTypes = 'Parameter/get-target-views',
  GetTargetSources = 'Parameter/get-target-sources',
  TargetDefinitionListGetByFilter = 'Target/get-by-filter',
  TargetDefinitionListGetExcelFile = 'Target/get-list-excel',
  TargetSourceViewForm = 'Target/get-view-form',
  CopyTarget = 'Approve/copy-target',
  GetTargetDetail = 'Target/get',
  TargetDefinitionAdd = 'Target/add',
  TargetDefinitionUpdate = 'Target/update',
  TargetSourceGetInsertForm = 'TargetDetail/get-insert-form',
  TargetSourceGetUpdateForm = 'TargetDetail/get-update-form',
  TargetSourceAdd = 'TargetDetail/add',
  TargetSourceUpdate = 'TargetDetail/update',

  CampaignReportFilterForm = 'Report/get-campaign-report-form',
  CampaignReportGetByFilter = 'Report/get-campaignreport-by-filter',
  CampaignReportGetByFilterExcelFile = 'Report/get-campaign-report-by-filter-excel',
  CustomerReportFilterForm = 'Report/get-customer-report-form',
  CustomerReportGetByFilter = 'Report/get-customer-report-by-filter',
  CustomerReportGetByFilterExcelFile = 'Report/get-customer-report-by-filter-excel',
  CustomerDetail = 'Report/get-customer-report-detail',
  EarningReportFilterForm = 'Report/get-earning-report-form',
  EarningReportGetByFilter = 'Report/get-earning-report-by-filter',
  EarningReportGetByFilterExcelFile = 'Report/get-earning-report-by-filter-excel',
  TargetReportFilterForm = 'Report/get-target-report-form',
  TargetReportGetByFilter = 'Report/get-targetreport-by-filter',
  TargetReportGetByFilterExcelFile = 'Report/get-target-report-by-filter-excel',
  CouponReportFilterForm = 'Report/get-coupon-report-form',
  CouponReportGetByFilter = 'Report/get-coupon-report-by-filter',
  CouponReportGetByFilterExcelFile = 'Report/get-coupon-report-by-filter-excel',
  InvitationReportFilterForm = 'Report/get-invitation-report-form',
  InvitationReportGetByFilter = 'Report/get-invitation-report-by-filter',
  InvitationReportGetByFilterExcelFile = 'Report/get-invitation-report-by-filter-excel',
  GetCouponReportDetail = 'Coupon/GetCustomerInfo',
  GetInvitationReportCampaignAchievements = 'Report/get-invitation-campaign-achievements',

  CampaignDefinitionApproveForm = 'Approve/get-campaign-form',
  CampaignDefinitionApprove = 'Approve/campaign',
  CampaignDefinitionDisapprove = 'Approve/campaign-disapprove',

  CampaignLimitsApproveForm = 'Approve/get-toplimit-form',
  CampaignLimitsApproveState = 'Approve/toplimit',

  TargetDefinitionApproveForm = 'Approve/get-target-form',
  TargetDefinitionApproveState = 'Approve/target',

  CustomerDefinitionList = 'CampaignIdentity/get-by-filter',
  CustomerDefinitionListGetExcelFile = 'CampaignIdentity/get-by-filter-excel',
  CustomerDefinitionGetUpdateForm = 'CampaignIdentity/get-update-form',
  CustomerDefinitionAddUpdate = 'CampaignIdentity/update',
  CustomerDefinitionDelete = 'CampaignIdentity/delete',

  CouponListFilterFormGiftTypeList = 'Parameter/get-coupon-gift-type-list',
  CouponList = 'Coupon/get-by-filter',
  CouponListGetExcelFile = 'Coupon/get-by-filter-excel',
  CouponListForCouponInfo = 'Coupon/get-lines-min-by-filter',
  CouponListForCouponInfoGetExcelFile = 'Coupon/get-lines-min-by-filter-excel',
  CouponInsertForm = 'Coupon/get-insert-form',
  CouponUpdateForm = 'Coupon/get-update-form',
  CouponAdd = 'Coupon/add',
  CouponUpdate = 'Coupon/update',
  CouponTransfer = 'Coupon/transfer',
  CompanyAdd = 'Company/add',
  CompanyList = 'Company/getall',

  CheckMGMCode = 'Coupon/check-mgm-code',
  CouponCampaignList = 'Coupon/get-campaign-list',
  CouponGetCampaign = 'Coupon/get-campaign',
  CouponGetCode = 'Coupon/get-code',
  SetMgmCode = 'Coupon/set-mgm-code',
  GetCustomerByMgmCode = 'Coupon/GetCustomerByMgmCode',

  MobileDashboard = 'Coupon/update-dashboardinfo',
  GetDashboardInfo = 'Coupon/get-dashboardinfo-update-form',

  AnnouncementsGetByFilter = 'announcement/get-by-filter',
  GetAnnouncementDetail = 'Campaign/get',
  AnnouncementGetInsertForm = 'announcement/get-insert-form',
  AnnouncementGetUpdateForm = 'announcement/get-update-form',
  AnnouncementAdd = 'announcement/add',
  AnnouncementUpdate = 'announcement/update',
  AnnouncementDelete = 'announcement/delete',

  AnnouncementApproveForm = 'Approve/get-announcement-form',
  AnnouncementApproveState = 'Approve/announcement',

  TemplateList = 'Template/get-by-filter',
  TemplateGet = 'Template/get',
  TemplateAdd = 'Template/add',
  TemplateUpdate = 'Template/update',
}
